services:
  frontend:
    container_name: frontend
    build: ./frontend
    command: npm run dev
    restart: always
    ports:
      - "5173:5173"  
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src

  backend:
    container_name: backend
    build: ./backend
    command: npm run dev
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - .env.docker-compose
    volumes:
      - ./backend/src:/server/src


  database:
    image: postgres:15
    container_name: database
    restart: always
    env_file:
      - .env.docker-compose
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/src/db/init:/docker-entrypoint-initdb.d


volumes:
  pgdata: